version: '3.8'

services:
  backend:
    image: sistema-familiar-backend:latest
    environment:
      # Conectar ao banco de dados externo existente
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM:-HS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
    networks:
      - sistema-familiar-network
      # Conectar à rede do banco de dados externo
      - db_network
      # Conectar à rede do Nginx externo
      - nginx_public
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    # Não expor portas diretamente - será acessado via Nginx externo

  frontend:
    image: sistema-familiar-frontend:latest
    networks:
      - sistema-familiar-network
      # Conectar à rede do Nginx externo
      - nginx_public
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    # Não expor portas diretamente - será acessado via Nginx externo

networks:
  sistema-familiar-network:
    driver: overlay
    attachable: true
  # Rede externa do banco de dados PostgreSQL
  db_network:
    external: true
    name: db_network
  # Rede externa do Nginx Proxy Manager
  nginx_public:
    external: true
    name: nginx_public

