version: '3.8'

services:
  backend:
    image: sistema-familiar-backend:latest
    environment:
      # Conectar ao banco de dados externo existente
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM:-HS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
    ports:
      - "8001:8001"
    networks:
      - sistema-familiar-network
      # Conectar à rede do banco de dados externo
      - db_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback

  frontend:
    image: sistema-familiar-frontend:latest
    ports:
      - "5173:80"
    networks:
      - sistema-familiar-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback

networks:
  sistema-familiar-network:
    driver: overlay
    attachable: true
  # Rede externa do banco de dados PostgreSQL
  db_network:
    external: true
    name: db_network

