# Generated by Django 4.2.10 on 2025-11-23 22:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='equipment_attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif'])], verbose_name='Arquivo')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='maintenance.equipment', verbose_name='Equipamento')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Upload por')),
            ],
            options={
                'verbose_name': 'Anexo do Equipamento',
                'verbose_name_plural': 'Anexos do Equipamento',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
